repos:
-   repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
    - id: black
      language_version: python3
-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    - id: flake8
      args: ["--max-line-length=89", "--ignore=E402,W504,W503,E501", "--exclude=test_*.py"]
-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.1
    hooks:
    - id: gitleaks
